server:
  type: default
  applicationConnectors:
    - type: http
      port: 8070
  adminConnectors:
    - type: http
      port: 8071

consumer:
  bootstrapServer: 127.0.0.1:9092
  consumerGroupId: consumer2
  topic: data-output
  deserializerClass: com.malwarebytes.model.TokenInfo

redis:
  type: basic
  name: my-redis-use-case
  node:
    type: redis
    node: "127.0.0.1:6379"
    clientName: person-app
  redisCodec:
    type: string
  clientResources:
    type: default
    commandLatencyCollector:
      type: default
      enabled: false