server:
  type: default
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091

consumer:
  bootstrapServer: 127.0.0.1:9092
  consumerGroupId: consumer1
  topic: data-input
  deserializerClass: com.malwarebytes.model.CardInfo


producer:
  bootstrapServer: 127.0.0.1:9092
  topic: data-output
  acks: all
  retries: 2147483647 # int max value
  maxInFlightRequestsPerConnection: 1
  maxPollBlockTime: 10s

redis:
  type: basic
  name: my-redis-use-case
  node:
    type: redis
    node: "127.0.0.1:6379"
    clientName: person-app
  redisCodec:
    type: string
  clientResources:
    type: default
    commandLatencyCollector:
      type: default
      enabled: false